config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get '/welcome/:first_name', to: 'static_pages#welcome'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  resources :users, only: [:new, :create, :show]
  resources :cities, only: [:show]
  resources :gossips do
    resources :comments, only: [:create, :destroy, :update, :edit]
    resources :likes, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :author, class_name: "User"
  # has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_table_gossip_tags, dependent: :destroy
  has_many :tags, through: :join_table_gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true,length: { in: 3..25}
  validates :content, presence: true
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  # belongs_to :comment, optional: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_table_private_message_users
  has_many :recipients, class_name: "User", through: :join_table_private_message_users
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city, optional: true
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :join_table_private_message_users
  has_many :received_messages, class_name: "PrivateMessage", through: :join_table_private_message_users  #,class_name: "JoinTablePrivateMessageUser"
  has_many :comments, foreign_key: 'author_id', class_name: "Comment", dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @city = City.find(params['id'])
    @id = params['id']
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:create, :edit, :destroy]
  before_action :user_is_author, only: [:edit, :destroy]

  def create
    @create_comment = Comment.new(
      author: current_user,
      gossip: Gossip.find_by_id(params[:id]),
      content: params[:comment_content]
    )
    if @create_comment.save
      flash[:comment_online] = "Le commentaire a été publié"
      redirect_to gossip_path(params[:id])
    else
      flash[:warning_comment] = "Le commentaire n'a pas pu être publié"
      redirect_to @create_comment.gossip
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @path = @comment.gossip
    @comment.destroy
    flash[:warning_delete_commentaire] = "Le commentaire a été supprimé"
    redirect_to @path
  end

  def update
    @update_comment = Comment.find(params[:id])
    if @update_comment.update(content: params[:gossip_content])
      flash[:update_comment] = " Le commentaire a bien été mis à jour !"
      redirect_to @update_comment.gossip
    else
      flash[:update_comment_warning] = " Le commentaire n'a pas pu être mis à jour !"
      render :edit
    end
  end

  def edit
    @edit_comm = Comment.find(params['id'])
  end

  private

  def user_is_author
    unless current_user == Comment.find(params[:id]).author
      flash[:not_author] = "Tu n'es pas l'auteur du commenntaire"
      redirect_to gossip_path(params[:gossip_id])
    end
  end

  def authenticate_user
    unless current_user
      flash[:not_logged_in] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :destroy]
  before_action :user_is_author, only: [:edit, :destroy]

  def index
    @gossips = Gossip.all
  end

  def create
    @create_gossip = Gossip.new(
      content: params[:gossip_content],
      title: params[:gossip_title],
      user: current_user
    )
    if @create_gossip.save
      JoinTableGossipTag.create(tag_id: params[:tag_id], gossip: @create_gossip)
      flash[:notice] = "Post successfully created"
      redirect_to @create_gossip
    else
      flash[:warning] = "Le potin n'a pas pu être créer"
      redirect_to new_gossip_path
    end
  end

  def new
    @post = Gossip.new
  end

  def edit
    @edit_goss = Gossip.find(params['id'])
  end

  def show
    @is_liked = Like.find_by(gossip_id: params[:id], user: current_user) != nil
    @goss = Gossip.find(params['id'])
    @id = params['id']
  end

  def update
    @update_gossip = Gossip.find(params[:id])
    if @update_gossip.update(content: params[:gossip_content],
      title: params[:gossip_title]
    )
      JoinTableGossipTag.create(tag_id: params[:tag_id], gossip: @update_gossip)
      flash[:update_success] = " Le potin a bien été mis à jour !"
      redirect_to @update_gossip
    else
      flash[:update_warning] = " Le potin n'a pas pu être mis à jour !"
      redirect_to @update_gossip
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    flash[:warning_delete] = "Le potin a été supprimé"
    redirect_to gossips_path
  end

  private

  def user_is_author
    unless current_user == Gossip.find(params[:id]).user
      flash[:not_author] = "Tu n'es pas l'auteur du potin"
      redirect_to gossip_path(params[:id])
    end
  end

  def authenticate_user
    unless current_user
      flash[:not_logged_in] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user, only: [:update, :create, :destroy]

  def create
    Like.create(user: current_user, gossip_id: params[:gossip_id])
    redirect_to request.referrer
  end

  def destroy
    Like.find(params[:id]).destroy
    redirect_to request.referrer
  end

  private

  def authenticate_user
    unless current_user
      flash[:not_logged_in] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @new_user = User.new
  end

  def create
    if City.where(name: params[:user_city] ).length.zero?
      @new_city = City.create(name: params[:user_city])
    end
    @create_user = User.new(
      last_name: params[:user_name].split(" ")[1],
      first_name: params[:user_name].split(" ")[0],
      email: params[:user_email],
      city_id: City.find_by(name: params[:user_city]).id,
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    )
    if @create_user.save
      flash[:success_create_user] = "Welcome #{@create_user.first_name}"
      session[:user_id] = @create_user.id
      redirect_to @create_user
    else
      flash[:warning_create_user] = "Le compte n'a pas pu être créer"
        @create_user.errors.full_messages.each do |message|
          puts message
        end
      redirect_to new_user_path
    end
  end


  def show
    @user = User.find(params['id'])
    @id = params['id']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_page_helper.rb
module DynamicPageHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def is_like?(id_gossip)
    Like.find_by(gossip_id: id_gossip, user: current_user)
  end

  def how_likes(id_gossip)
    Like.where(gossip_id: id_gossip).length
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8 />
    <title>City page</title>
  </head>
  <body>

    <main role="main">
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3"><%= @city.name %></h1>
          <hr>
          <hr>
        </div>
        <div class="container">
          <h1 class="display-5">Dans cette ville, ont été postés les potins suivants :</h1>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <% @city.gossips.each do |gossip| %>
          <div class="col-md-4">
            <div class="title_gossip">
              <h2>Potin n°<%= gossip.id%> :</h2>
              <% if session[:user_id]%>
                <% if like = is_like?(gossip.id)%>
                  <h2><a class=" heart heart_index" href="<%= gossip_like_path(gossip_id: gossip.id, id: like.id)  %>" role="button" data-method="delete"><i class="fas fa-heart"></i><span class="tooltiptext">J'aime déjà</span></a></h2>
                <% else %>
                  <h2><a class=" heart heart_index" href="<%= gossip_likes_path(gossip.id) %>" role="button" data-method="create"><i class="fas fa-heart-broken"></i><span class="tooltiptext">Aimer ce potin</span></a></h2>
                <% end %>
              <% end %>
            </div>
            L'utilisateur : <%= link_to "#{gossip.user.first_name} #{gossip.user.last_name}", user_path(gossip.user.id) %><br>
            A posté le potin : <%= link_to gossip.title, gossip_path(gossip.id)%>
            <p><a class="btn btn-secondary" href="<%= gossip_path(gossip.id)%>" role="button">View details &raquo;</a></p>
          </div>
          <%end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/comments/edit.html.erb
<html>
  <body>
    <% if flash[:update_comment_warning] %>
    <div class='alert alert-danger' role='alert'>
      <%= flash[:update_comment_warning] %>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span class="close-button" aria-hidden='true'>&times</span>
      </button>
    </div>
    <% end %>
    <main role="main">
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Ah mince, ce commentaire contient un erreur ?!?!?</h1>
          <h2 class="display-5">Heureusement que tu es là pour corriger ça  !!! Modifie-le ou supprime-le!</h2>
          <hr>
          <hr>

        </div>
        <div class="container">
          <div class="form">

            <%= form_tag url_for(action: 'update'), method: "patch" do %>

            <div class="form-item">
              <%= label_tag 'Contenu du potin' %>
              <%= text_area_tag 'gossip_content', @edit_comm.content %>
            </div>

            <div class="form-item">
              <%= submit_tag "Mettre à jour le commentaire" %>
            </div>

            <% end %>
          </div>
        </div>
        <p><a
          class="btn btn-danger btn-lg"
          href="<%=gossip_comment_path(id: @edit_comm, gossip_id: @edit_comm.gossip.id)%>"
          rel="nofollow"
          data-method="delete"
          data-confirm="Es-tu sûr de vouloir supprimer le commentaire?"
          role="button">Supprimer le commentaire &raquo;
        </a></p>


      </div>
    </main>
  </body>
</html>

app/views/gossips/edit.html.erb
<html>
  <body>
    <main role="main">
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Ah mince, ce potin contient un erreur ?!?!?</h1>
          <h2 class="display-5">Heureusement que tu es là pour corriger ça  !!!</h2>
          <hr>
        </div>
        <div class="container">
          <div class="form">
            <%= form_tag url_for(action: 'update'), method: "patch" do %>
            <div class="form-item">
              <%= label_tag 'Titre du Potin' %>
              <%= text_field_tag 'gossip_title', @edit_goss.title %>
            </div>
            <div class="form-item">
              <%= label_tag 'Contenu du potin' %>
              <%= text_area_tag 'gossip_content', @edit_goss.content %>
            </div>
            <div class="form-item">
              <%= submit_tag "Mettre à jour le potin" %>
            </div>
            <div class="form-item">
              <%=select_tag "tag_id", options_from_collection_for_select(Tag.all, "id", "title"), include_blank: true%>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/gossips/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8 />
    <title>Gossip accueil</title>
  </head>
  <body>

    <% if flash[:warning_delete] %>
    <div class='alert alert-warning' role='alert'>
      <%= flash[:warning_delete] %>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button>
    </div>
    <% end %>


    <main role="main">
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">La super page d'accueil de The Gossip Project</h1>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <% @gossips.each do |gossip| %>
          <div class="col-md-4">
            <div class="title_gossip">
              <h2>Potin n°<%= gossip.id%> :</h2>
              <% if session[:user_id]%>
                <% if like = is_like?(gossip.id)%>
                  <h2><a class=" heart heart_index" href="<%= gossip_like_path(gossip_id: gossip.id, id: like.id)  %>" role="button" data-method="delete"><i class="fas fa-heart"></i><span class="tooltiptext">J'aime déjà</span></a></h2>
                <% else %>
                  <h2><a class=" heart heart_index" href="<%= gossip_likes_path(gossip.id) %>" role="button" data-method="create"><i class="fas fa-heart-broken"></i><span class="tooltiptext">Aimer ce potin</span></a></h2>
                <% end %>
              <% end %>
            </div>
            L'utilisateur : <%= link_to "#{gossip.user.first_name} #{gossip.user.last_name}", user_path(gossip.user.id) %><br>
            A posté le potin : <%= link_to gossip.title, gossip_path(gossip.id)%><br>
            <i class="fas fa-comment"></i> (<%= gossip.comments.length%>) <i class="fas fa-heart"></i> (<%= how_likes(gossip)%>) 
            <p><a class="btn btn-secondary" href="<%= gossip_path(gossip.id)%>" role="button">View details &raquo;</a></p>
          </div>
          <%end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/gossips/new.html.erb
<html>
  <body>
    <% if flash[:warning] %>
    <div class='alert alert-danger' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong>Warning!</strong> <%=flash[:warning]%></div>
    <% end %>
    <main role="main">
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Youpi un nouveau potin !!!</h1>

        </div>
        <div class="container">
          <div class="form">

          <%= form_tag url_for(action: 'create'), method: "post" do %>

          <div class="form-item">
            <%= label_tag 'Titre du nouveau Potin' %>
            <%= text_field_tag 'gossip_title', @post.title %>
          </div>

          <div class="form-item">
            <%= label_tag 'Contenu du nouveau potin' %>
            <%= text_area_tag 'gossip_content', @post.content %>
          </div>

          <div class="form-item">
            <%=select_tag "tag_id", options_from_collection_for_select(Tag.all, "id", "title"), include_blank: 'Tags'%>
          </div>

          <div class="form-item">
            <%= submit_tag "Créer le potin" %>
          </div>

          <% end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/gossips/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8 />
    <title>Gossip page</title>
  </head>
  <body>
    <% if flash[:notice] %>
    <div class='alert alert-success' role='alert'>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button><strong>Success!</strong> <%= flash[:notice] %>
    </div>
    <% end %>
    <% if flash[:update_success] %>
    <div class='alert alert-success' role='alert'>
      <strong>Success! </strong> <%= flash[:update_success] %>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span class="close-button" aria-hidden='true'>&times</span>
      </button>
    </div>
    <% end %>
    <% if flash[:comment_online] %>
    <div class='alert alert-success' role='alert'>
      <strong>Success! </strong> <%= flash[:comment_online] %>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span class="close-button" aria-hidden='true'>&times</span>
      </button>
    </div>
    <% end %>
    <% if flash[:warning_comment] %>
    <div class='alert alert-danger' role='alert'>
      <%= flash[:warning_comment] %>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span class="close-button" aria-hidden='true'>&times</span>
      </button>
    </div>
    <% end %>
    <% if flash[:update_warning] %>
    <div class='alert alert-danger' role='alert'>
      <%= flash[:update_warning] %>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span class="close-button" aria-hidden='true'>&times</span>
      </button>
    </div>
    <% end %>
    <% if flash[:update_comment] %>
    <div class='alert alert-success' role='alert'>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button><strong>Success!</strong> <% flash[:update_comment] %>
    </div>
    <% end %>
    <% if flash[:not_author] %>
    <div class='alert alert-danger' role='alert'>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button> <%= flash[:not_author] %>
    </div>
    <% end %>


    <main role="main">
      <div class="jumbotron">
        <div class="container">
          <div class="title_gossip">
            <h1 class="display-3">
              Potin n° <%= @id%>
            </h1>
            <h1 class="display-3 heart">
              <% if session[:user_id]%>
                <% if like = is_like?(@goss)%>
                  <a href="<%= gossip_like_path(gossip_id: @goss.id, id: like.id)  %>" role="button" data-method="delete"><i class="fas fa-heart"></i></a><span class="tooltiptext">J'aime déjà</span>
                <% else %>
                  <a href="<%= gossip_likes_path(@goss.id) %>" role="button" data-method="create"><i class="fas fa-heart-broken"></i></a><span class="tooltiptext">Aimer ce potin</span>
                <% end %>
              <% end %>
            </h1>
          </div>
          <hr>
          <p> Écrit par <%= link_to "#{@goss.user.first_name} #{@goss.user.last_name}", user_path(@goss.user.id) %>
             le <%= @goss.created_at.strftime('%D')%> à <%= @goss.created_at.strftime('%T')%></p>
          <p>Le potin concerne la ville : <%= link_to @goss.user.city.name, city_path(@goss.user.city.id)%></p>
        </div>
        <div class="container">
          <h1 class="display-5">Titre du potin :  <%= @goss.title%> </h1>
          <hr>
          <p><%= @goss.content %></p>
          <h5 class="display-6">Tags associés :</h5>
          <ul type = "circle">
          <%@goss.tags.each do |t| %>
          <li><%=t.title%></li>
          <%end %>
          </ul>
          <hr>
          <% if current_user == @goss.user%>
            <h4 class="display-5">Espace édition :</h4>
            <p><a class="btn btn-primary btn-lg" href="<%=edit_gossip_path(@goss.id)%>" role="button">Edit &raquo;</a></p>
            <p><a
              class="btn btn-primary btn-lg"
              href="<%=gossip_path(@goss.id)%>"
              rel="nofollow"
              data-method="delete"
              data-confirm="Es-tu sûr de vouloir supprimer le potin?"
              role="button">Supprimer le potin &raquo;
            </a></p>
            <hr>
          <% end %>
          <h4 class="display-5">Espace commentaires :</h4>
          <div class="container">
            <div class="comment">
              <%= form_tag url_for(:controller => 'comments', :action => 'create', :id => @goss.id, gossip_id: params[:id]), method: "post" do %>
              <div class="comment-item">
                <%= text_area_tag 'comment_content', "Rédige ton commentaire" %>
              </div>
              <div class="comment-validation">
                <%= submit_tag "Publier le commentaire" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <% @goss.comments.each do |com| %>
          <div class="col-md-4">
            <h2>Commentaire de </h2>
            <h3><%= link_to "#{com.author.first_name} #{com.author.last_name}" , user_path(com.author.id)%> </h3>
            <%= com.content %>
            <% if current_user == com.author%>
              <p><a class="btn btn-secondary" href="<%= edit_gossip_comment_path(:id => com.id, gossip_id: params[:id])%>" role="button">Éditer le commentaire &raquo;</a></p>
            <%end %>
          </div>
          <%end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/users/new.html.erb
<html>
  <body>
    <% if flash[:warning_create_user] %>
    <div class='alert alert-danger' role='alert'>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button> <%= flash[:warning_create_user] %>
    </div>
    <% end %>
    <main role="main">
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Cool un nouveau membre !!!<i class="fas fa-heart"></i></h1>

        </div>
        <div class="container">
          <div class="form">
          <%= form_tag url_for(action: 'create'), method: "post" do %>
          <div class="form-item">
            <%= text_field_tag 'user_name', nil, :placeholder => 'Prénom Nom' %>
          </div>
          <div class="form-item">
            <%= text_field_tag 'user_city', nil, :placeholder => 'ville' %>
          </div>
          <div class="form-item">
            <%= text_field_tag 'user_email', nil, :placeholder => "Email" %>
          </div>
          <div class="form-item">
            <%= label_tag 'Mot de passe' %>
            <%= password_field_tag 'password', nil, :placeholder => 'Mot de passe' %>
          </div>
          <div class="form-item">
            <%= password_field_tag 'password_confirmation', nil, :placeholder => 'Confirmation mot de passe' %>
          </div>
          </div>
          <div class="form-item">
            <%= submit_tag "Créer le compte" %>
          </div>
          <% end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8 />
    <title>Gossip page</title>
  </head>
  <body>
    <% if flash[:success_create_user] %>
    <div class='alert alert-success' role='alert'>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button><strong>Success!</strong> <%= flash[:success_create_user] %>
    </div>
    <% end %>
    <main role="main">
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3"><%= @user.first_name %> <%= @user.last_name %></h1>
          <hr>
          <h2 class="display-4"> Description :</h2>
          <p><%= @user.description %></p>
          <hr>
          <h3 class="display-4">Informations complémentaires :</h3>
            <p> Email : <%= @user.email %></p>
            <p> Age : <%= @user.age %></p>
            <p>Habite : <%= link_to @user.city.name, city_path(@user.city.id)%></p>
            <p>Membre depuis le <%= @user.created_at.strftime('%D')%> à <%= @user.created_at.strftime('%T')%></p>
        </div>
        <hr>
        <div class="container">
          <h1 class="display-5">Ce membre a posté les potins :</h1>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <% @user.gossips.each do |gossip| %>
          <div class="col-md-4">
            <div class="title_gossip">
              <h2>Potin n°<%= gossip.id%> :</h2>
              <% if session[:user_id]%>
                <% if like = is_like?(gossip.id)%>
                  <h2><a class=" heart heart_index" href="<%= gossip_like_path(gossip_id: gossip.id, id: like.id)  %>" role="button" data-method="delete"><i class="fas fa-heart"></i><span class="tooltiptext">J'aime déjà</span></a></h2>
                <% else %>
                  <h2><a class=" heart heart_index" href="<%= gossip_likes_path(gossip.id) %>" role="button" data-method="create"><i class="fas fa-heart-broken"></i><span class="tooltiptext">Aimer ce potin</span></a></h2>
                <% end %>
              <% end %>
            </div>
            <p>A posté le potin : <%= link_to gossip.title, gossip_path(gossip.id)%></p>
          </div>
          <%end %>
        </div>
      </div>
    </main>
  </body>
</html>