config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get '/welcome/:first_name', to: 'static_pages#welcome'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  resources :users, only: [:new, :create, :show]
  resources :cities, only: [:show]
  resources :gossips do
    resources :comments, only: [:create, :destroy, :update, :edit]
    resources :likes, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :author, class_name: "User"
  # has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_table_gossip_tags, dependent: :destroy
  has_many :tags, through: :join_table_gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true,length: { in: 3..25}
  validates :content, presence: true
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  # belongs_to :comment, optional: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_table_private_message_users
  has_many :recipients, class_name: "User", through: :join_table_private_message_users
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city, optional: true
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :join_table_private_message_users
  has_many :received_messages, class_name: "PrivateMessage", through: :join_table_private_message_users  #,class_name: "JoinTablePrivateMessageUser"
  has_many :comments, foreign_key: 'author_id', class_name: "Comment", dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user, only: [:update, :create, :destroy]

  def create
    Like.create(user: current_user, gossip_id: params[:gossip_id])
    redirect_to request.referrer
  end

  def destroy
    Like.find(params[:id]).destroy
    redirect_to request.referrer
  end

  private

  def authenticate_user
    unless current_user
      flash[:not_logged_in] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @new_user = User.new
  end

  def create
    if City.where(name: params[:user_city] ).length.zero?
      @new_city = City.create(name: params[:user_city])
    end
    @create_user = User.new(
      last_name: params[:user_name].split(" ")[1],
      first_name: params[:user_name].split(" ")[0],
      email: params[:user_email],
      city_id: City.find_by(name: params[:user_city]).id,
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    )
    if @create_user.save
      flash[:success_create_user] = "Welcome #{@create_user.first_name}"
      session[:user_id] = @create_user.id
      redirect_to @create_user
    else
      flash[:warning_create_user] = "Le compte n'a pas pu être créer"
        @create_user.errors.full_messages.each do |message|
          puts message
        end
      redirect_to new_user_path
    end
  end


  def show
    @user = User.find(params['id'])
    @id = params['id']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_page_helper.rb
module DynamicPageHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def is_like?(id_gossip)
    Like.find_by(gossip_id: id_gossip, user: current_user)
  end

  def how_likes(id_gossip)
    Like.where(gossip_id: id_gossip).length
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="http://www.jacklmoore.com/colorbox/example1/colorbox.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

  </head>

  <body>
    <header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" id='nav'>
  <a class="navbar-brand" href="/">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/team">The team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Nous contacter</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=new_gossip_path%>">Créer un potin</a>
      </li>
      <li class="nav-item dropdown">
        <a
        class="nav-link dropdown-toggle"
        href="#" id="navbarDropdown"
        role="button"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
        >Potins</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Gossip.all.each do |gossip| %>
          <a class="dropdown-item" href="<%=gossip_path(gossip.id)%>">Potin n° <%=gossip.id%></a>
          <%end %>
        </div>
      </li>
      <% if session[:user_id]%>
        <li class="nav-item">
          <a class="nav-link" href="<%=user_path(current_user)%>">Mon profil</a>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <li>
        <% if session[:user_id]%>
          <a
            class="nav-link my-2 my-lg-0"
            href="<%=session_path(session[:user_id])%>"
            data-method="delete"
            data-confirm="Es-tu sûr de vouloir te déconnecter?">Se déconnecter
          </a>
          <% else %>
          <li class="nav-item dropdown">
            <a
            class="nav-link dropdown-toggle"
            href="#" id="navbarDropdown"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            >S'inscrire / Se connecter</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="<%=new_user_path%>">S'inscrire</a>
              <hr>
              <a class="dropdown-item" href="<%=new_session_path%>" data-method="delete">Se connecter</a>
            </div>
          </li>
        <% end %>
    </ul>
  </div>
</nav>
</header>

<div class="yield">
  <%= yield %>
</div>



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>

</html>